<%
Function GetFileIcon(strFilename)
	strFilename=Split(LCase(strFilename),".")
	Select Case strFilename(Ubound(strFilename))
	Case "asp"
		GetFileIcon="asp.gif"
	Case "aspx"
		GetFileIcon="asp.gif"
	Case "jsp"
		GetFileIcon="asp.gif"
	Case "html"
		GetFileIcon="html.gif"
	Case "shtml"
		GetFileIcon="html.gif"
	Case "htm"
		GetFileIcon="html.gif"
	Case "shtm"
		GetFileIcon="html.gif"
	Case "xml"
		GetFileIcon="xml.gif"
	Case "bmp"
		GetFileIcon="bmp.gif"
	Case "doc"
		GetFileIcon="doc.gif"
	Case "gif"
		GetFileIcon="gif.gif"
	Case "ico"
		GetFileIcon="ico.gif"
	Case "jpg"
		GetFileIcon="jpg.gif"
	Case "js"
		GetFileIcon="js.gif"
	Case "mdb"
		GetFileIcon="mdb.gif"
	Case "mp3"
		GetFileIcon="media.gif"
	Case "wma"
		GetFileIcon="media.gif"
	Case "mid"
		GetFileIcon="media.gif"
	Case "png"
		GetFileIcon="png.gif"
	Case "rar"
		GetFileIcon="rar.gif"
	Case "swf"
		GetFileIcon="swf.gif"
	Case "txt"
		GetFileIcon="txt.gif"
	Case "xls"
		GetFileIcon="xls.gif"
	Case "xlt"
		GetFileIcon="xlt.gif"
	Case "zip"
		GetFileIcon="zip.gif"
	Case "exe"
		GetFileIcon="exe.gif"
	Case "dll"
		GetFileIcon="dll.gif"
	Case Else
		GetFileIcon="other.gif"
	End Select
End Function
%> 
