document.writeln('<table width=\"98%\" border=\"0\" align=\"center\">')
document.writeln('<form id=\"SearchForm\" name=\"SearchForm\" method=\"get\" action=\"/item/index.asp\">')
document.writeln('  <tr>')
document.writeln('    <td align=\"center\"><select name=\"t\">')
document.writeln('        <option value=\"1\">标 题</option>')
document.writeln('        <option value=\"2\">内 容</option>')
document.writeln('        <option value=\"3\">作 者</option>')
document.writeln('        <option value=\"4\">录入者</option>')
document.writeln('        <option value=\"5\">关键字</option>')
document.writeln('      </select>')
document.writeln('        <select name=\"tid\" style=\"width:150px\">')
document.writeln('          <option value=\"0\" selected=\"selected\">所有栏目</option>')
document.writeln('<option value=\'20136090520346\'>栏目中心 </option><option value=\'20137762162591\'>──关于我们 </option><option value=\'20131252015464\'>──企业资质 </option><option value=\'20130066233211\'>──产品中心 </option><option value=\'20137695870291\'>────家用空调 </option><option value=\'20139379194853\'>────中央空调 </option><option value=\'20138953144704\'>────小型家电 </option><option value=\'20138112059345\'>──企业新闻 </option><option value=\'20133678193158\'>──领导讲话 </option><option value=\'20137131250565\'>──公司活动 </option>        </select>')
document.writeln('        <input name=\"key\" type=\"text\" class=\"textbox\"  value=\"关键字\" onfocus=\"this.select();\"/>')
document.writeln('        <input name=\"ChannelID\" value=\"1\" type=\"hidden\" />')
document.writeln('        <input type=\"submit\" class=\"inputButton\" name=\"sbtn\" value=\"搜 索\" /></td>')
document.writeln('  </tr>')
document.writeln('</form>')
document.writeln('</table>')
