<html>
<head>
<title>丽江分行-网络办公系统</title>
<meta http-equiv="Content-Type" content="text/html; charset=gb2312">
<script language="JavaScript">
<!--
<!--
function MM_reloadPage(init) {  //reloads the window if Nav4 resized
  if (init==true) with (navigator) {if ((appName=="Netscape")&&(parseInt(appVersion)==4)) {
    document.MM_pgW=innerWidth; document.MM_pgH=innerHeight; onresize=MM_reloadPage; }}
  else if (innerWidth!=document.MM_pgW || innerHeight!=document.MM_pgH) location.reload();
}
MM_reloadPage(true);
// -->

function MM_swapImgRestore() { //v3.0
  var i,x,a=document.MM_sr; for(i=0;a&&i<a.length&&(x=a[i])&&x.oSrc;i++) x.src=x.oSrc;
}
//-->
</script>
<script language="JavaScript">
<!--
function MM_openBrWindow(theURL,winName,features) { //v2.0
  window.open(theURL,winName,features);
}

function MM_preloadImages() { //v3.0
  var d=document; if(d.images){ if(!d.MM_p) d.MM_p=new Array();
    var i,j=d.MM_p.length,a=MM_preloadImages.arguments; for(i=0; i<a.length; i++)
    if (a[i].indexOf("#")!=0){ d.MM_p[j]=new Image; d.MM_p[j++].src=a[i];}}
}

function MM_findObj(n, d) { //v4.0
  var p,i,x;  if(!d) d=document; if((p=n.indexOf("?"))>0&&parent.frames.length) {
    d=parent.frames[n.substring(p+1)].document; n=n.substring(0,p);}
  if(!(x=d[n])&&d.all) x=d.all[n]; for (i=0;!x&&i<d.forms.length;i++) x=d.forms[i][n];
  for(i=0;!x&&d.layers&&i<d.layers.length;i++) x=MM_findObj(n,d.layers[i].document);
  if(!x && document.getElementById) x=document.getElementById(n); return x;
}

function MM_swapImage() { //v3.0
  var i,j=0,x,a=MM_swapImage.arguments; document.MM_sr=new Array; for(i=0;i<(a.length-2);i+=3)
   if ((x=MM_findObj(a[i]))!=null){document.MM_sr[j++]=x; if(!x.oSrc) x.oSrc=x.src; x.src=a[i+2];}
}
//-->
</script>
<link rel="stylesheet" href="images/input.css" type="text/css">
</head>

<body bgcolor="#0066CC" text="#000000" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0" scroll=no onLoad="MM_preloadImages('images/ps2.gif','images/bb2.gif')">
<table width="100%" border="0" cellspacing="0" cellpadding="0" height="100%">
  <tr> 
    <td align="left" valign="middle">
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
     <tr><td><DIV align=center><FONT color=#ff0000 face=华文行楷 size=6>中国农业银行丽江地区分行网络办公系统</font></DIV></td></tr>
            <tr><td><center><FONT color=#ff0000>============================================================================</td></tr>  
       <tr><td><DIV align=center><FONT color=#EEEEEEE face=宋体 size=3>《本系统仅供丽江分行及辖内各支行机关、各营业机构日常办公及管理的需要》</font></DIV></td></tr>
        <tr> 
          <td align="left" valign="bottom"><img src="images/index_r1_c1.gif" width="297" height="125"><img src="images/index_r1_c2.gif" width="462" height="125"></td>
        </tr>
       <tr><td><DIV align=center><FONT color=#EEEEEEE face=宋体 size=3>本系统提供：统计查询　信贷查询　公文查询　电话查询　内部交流　资料上报　公文处理　个人邮件等服务</font></DIV></td></tr> 
        <tr> 
          <td align="left" valign="top" background="images/index_r2_c5.gif"><img src="images/index_r2_c1.gif" width="297" height="181"><img src="images/index_r2_c2.gif" width="462" height="181"></td>
        </tr>
        <tr> 
          <td align="left" valign="top"><img src="images/index_r3_c1.gif" width="393" height="57"><img src="images/index_r3_c3.gif" width="280" height="57">
            <div id="Layer1" style="position:absolute; width:19px; height:23px; z-index:2">
              <div id="Layer4" style="position:absolute; width:200px; height:115px; z-index:3; top: -200; left: -300"><object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"  width="250" height="181">
                  <param name=movie value="images/back1.swf">
                  <param name=quality value=high>
				  <PARAM NAME=menu VALUE=false>
				  <PARAM NAME=wmode VALUE=transparent>
                  <embed src="images/back1.swf" quality=high type="application/x-shockwave-flash" width="250" height="181">
                  </embed> 
                </object></div>
              <div id="Layer3" style="position:absolute; width:100px; height:41px; z-index:4; left: -30px; top: -45" class="input"> 
               
                </div>
              <div id="Layer2" style="position:absolute; width:300px; height:51px; z-index:5; left: -222px; top: -50; overflow: visible"> 
                <form name="form1" method="post" action="checklogin.asp">
                  <table width="100%" border="0" cellspacing="0" cellpadding="0" height="50">
                    <tr> 
                      <td align="left" valign="top"> 
                       <FONT color=#ff0000> 姓名：<input type="text" name="username" class="input">
                        <a href="#" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('login','','images/bb2.gif',1)">
                      </td>
                    </tr>
                    <tr> 
                      <td align="left" valign="top" height="20"> 
                        <FONT color=#ff0000>密码：<input type="password" name="password" class="input">
                        <a href="#" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('pass','','images/ps2.gif',1)" onClick="MM_openBrWindow('register.asp','','width=500,height=450')"><br><img name="pass" border="0" src="images/ps.gif" width="80" height="20"></a>　<input type=image name="login" border="0" src="images/bb.gif" width="50" height="20"></a>  
                      </td>
                    </tr>
                  </table>
                </form>
              </div> 
            </div>
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>
</body>
</html>
