document.writeln('<table width="100%" border="0" cellspacing="0" cellpadding="3">');
document.writeln('<tr>');
document.writeln('<td valign="top" width="100%">');
document.writeln('<div class="classtitle" style="font-weight:bold"><img src="/images/gw12.gif" align="absmiddle">&nbsp;<a href="http://192.168.1.101/shop/showbrand.asp?id=1248">潮流男士</a></div>');
document.writeln('</td>');
document.writeln('</tr>');
document.writeln('<tr>');
document.writeln('<td valign="top" width="100%">');
document.writeln('<div class="classtitle" style="font-weight:bold"><img src="/images/gw12.gif" align="absmiddle">&nbsp;<a href="http://192.168.1.101/shop/showbrand.asp?id=1247">美丽女士</a></div>');
document.writeln('</td>');
document.writeln('</tr>');
document.writeln('<tr>');
document.writeln('<td valign="top" width="100%">');
document.writeln('<div class="classtitle" style="font-weight:bold"><img src="/images/gw12.gif" align="absmiddle">&nbsp;<a href="http://192.168.1.101/shop/showbrand.asp?id=1246">美妆饰品箱包</a></div>');
document.writeln('</td>');
document.writeln('</tr>');
document.writeln('<tr>');
document.writeln('<td valign="top" width="100%">');
document.writeln('<div class="classtitle" style="font-weight:bold"><img src="/images/gw12.gif" align="absmiddle">&nbsp;<a href="http://192.168.1.101/shop/showbrand.asp?id=1245">手机数码家电</a></div>');
document.writeln('</td>');
document.writeln('</tr>');
document.writeln('<tr>');
document.writeln('<td valign="top" width="100%">');
document.writeln('<div class="classtitle" style="font-weight:bold"><img src="/images/gw12.gif" align="absmiddle">&nbsp;<a href="http://192.168.1.101/shop/showbrand.asp?id=1244">运动户外车品</a></div>');
document.writeln('</td>');
document.writeln('</tr>');
document.writeln('<tr>');
document.writeln('<td valign="top" width="100%">');
document.writeln('<div class="classtitle" style="font-weight:bold"><img src="/images/gw12.gif" align="absmiddle">&nbsp;<a href="http://192.168.1.101/shop/showbrand.asp?id=1243">家居母婴美食</a></div>');
document.writeln('</td>');
document.writeln('</tr>');
document.writeln('<tr>');
document.writeln('<td valign="top" width="100%">');
document.writeln('<div class="classtitle" style="font-weight:bold"><img src="/images/gw12.gif" align="absmiddle">&nbsp;<a href="http://192.168.1.101/shop/showbrand.asp?id=937">品牌馆</a></div>');
document.writeln('</td>');
document.writeln('</tr>');
document.writeln('</table>');
