document.writeln('<table width="100%" border="0" cellspacing="0" cellpadding="3">');
document.writeln('<tr>');
document.writeln('<td valign="top" width="100%">');
document.writeln('<div class="classtitle" style="font-weight:bold"><img src="/images/default/arrow_r.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=1248" target="_blank">潮流男士</a></div>');
document.writeln('<div class="list"><a href="/Item/list.asp?id=1251" target="_blank">畅销热卖</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=1250" target="_blank">男装专区</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=1249" target="_blank">男鞋专区</a>&nbsp;</div>');
document.writeln('</td>');
document.writeln('</tr>');
document.writeln('<tr>');
document.writeln('<td valign="top" width="100%">');
document.writeln('<div class="classtitle" style="font-weight:bold"><img src="/images/default/arrow_r.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=1247" target="_blank">美丽女士</a></div>');
document.writeln('<div class="list"><a href="/Item/list.asp?id=1272" target="_blank">上衣</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=1271" target="_blank">裤子</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=1270" target="_blank">内衣</a>&nbsp;</div>');
document.writeln('</td>');
document.writeln('</tr>');
document.writeln('<tr>');
document.writeln('<td valign="top" width="100%">');
document.writeln('<div class="classtitle" style="font-weight:bold"><img src="/images/default/arrow_r.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=1246" target="_blank">美妆饰品箱包</a></div>');
document.writeln('<div class="list"><a href="/Item/list.asp?id=1293" target="_blank">饰品手表</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=1292" target="_blank">皮具箱包</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=1291" target="_blank">美妆</a>&nbsp;</div>');
document.writeln('</td>');
document.writeln('</tr>');
document.writeln('<tr>');
document.writeln('<td valign="top" width="100%">');
document.writeln('<div class="classtitle" style="font-weight:bold"><img src="/images/default/arrow_r.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=1245" target="_blank">手机数码家电</a></div>');
document.writeln('<div class="list"><a href="/Item/list.asp?id=1314" target="_blank">家用电器</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=1313" target="_blank">手机数码</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=1312" target="_blank">配件硬件</a>&nbsp;</div>');
document.writeln('</td>');
document.writeln('</tr>');
document.writeln('<tr>');
document.writeln('<td valign="top" width="100%">');
document.writeln('<div class="classtitle" style="font-weight:bold"><img src="/images/default/arrow_r.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=1244" target="_blank">运动户外车品</a></div>');
document.writeln('<div class="list"><a href="/Item/list.asp?id=1335" target="_blank">运动鞋服</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=1334" target="_blank">健身器材</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=1333" target="_blank">车品户外</a>&nbsp;</div>');
document.writeln('</td>');
document.writeln('</tr>');
document.writeln('<tr>');
document.writeln('<td valign="top" width="100%">');
document.writeln('<div class="classtitle" style="font-weight:bold"><img src="/images/default/arrow_r.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=1243" target="_blank">家居母婴美食</a></div>');
document.writeln('<div class="list"><a href="/Item/list.asp?id=1356" target="_blank">家居家装</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=1355" target="_blank">母婴童装</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=1354" target="_blank">美食世界</a>&nbsp;</div>');
document.writeln('</td>');
document.writeln('</tr>');
document.writeln('<tr>');
document.writeln('<td valign="top" width="100%">');
document.writeln('<div class="classtitle" style="font-weight:bold"><img src="/images/default/arrow_r.gif" align="absmiddle">&nbsp;<a href="/shop/showbrand.asp?id=0" target="_blank">品牌馆</a></div>');
document.writeln('</td>');
document.writeln('</tr>');
document.writeln('</table>');
